# netlify.toml
[build]
  functions = "netlify/functions"
  publish = "."
  command = "echo 'No build command needed'"
  
[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

# For SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"